# Generated by Django 5.0.7 on 2024-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_question_userdetails_user_submission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
