# Generated by Django 5.0.7 on 2024-08-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userdetails_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('ipaddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ip_table',
            },
        ),
    ]
